In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray',arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [10]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez('ziparray.npz', x = arr1, y = arr2)

In [20]:
archive_array = np.load('ziparray.npz')
archive_array

In [14]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [19]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])