In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([ 1.82776183,  0.44223791,  1.20848649, -1.25853652,  0.89210901,
       -0.6413939 ,  1.90231869, -1.27325081,  0.6271183 ,  0.43620649])

In [9]:
B = np.random.randn(10)
B

array([ 0.65421298,  0.5736077 , -1.33715917, -0.65898658,  0.03425814,
        1.16628693,  0.55407871,  1.15983739, -1.35092549, -1.23337182])

In [10]:
np.add(A,B)

array([ 2.48197481,  1.0158456 , -0.12867268, -1.9175231 ,  0.92636715,
        0.52489304,  2.4563974 , -0.11341342, -0.72380719, -0.79716533])

In [12]:
np.maximum(A,B)

array([ 1.82776183,  0.5736077 ,  1.20848649, -0.65898658,  0.89210901,
        1.16628693,  1.90231869,  1.15983739,  0.6271183 ,  0.43620649])

In [14]:
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True